site_name: EPSM Documentation
site_description: Documentation for the Energy Performance Simulation Manager (EPSM)
docs_dir: docs
site_url: https://snjsomnath.github.io/epsm/
theme:
  name: material
nav:
  - Home: index.md
  - Project README: PROJECT_README.md
  - Getting Started: GETTING_STARTED.md
  - Development: DEVELOPMENT.md
  - API: API.md
  - Architecture: ARCHITECTURE.md
  - Deployment: DEPLOYMENT.md
  - Scripts: SCRIPTS.md
  - Results DB: RESULTS_DB_SETUP.md
  - Organization: ORGANIZATION.md
  - Archive:
    - PHASE_3_COMPLETE: archive/PHASE_3_COMPLETE.md
    - RESTRUCTURE_PLAN: archive/RESTRUCTURE_PLAN.md
    - Index: archive/index.md
  - Sidebar: _sidebar.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
