# Generated by Django 3.2.25 on 2025-05-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('element_type', models.CharField(choices=[('wall', 'Wall'), ('roof', 'Roof'), ('floor', 'Floor'), ('ceiling', 'Ceiling'), ('window', 'Window')], max_length=20)),
                ('is_window', models.BooleanField(default=False)),
                ('ep_construction_name', models.CharField(blank=True, max_length=255, null=True)),
                ('u_value_w_m2k', models.FloatField()),
                ('gwp_kgco2e_per_m2', models.FloatField()),
                ('cost_sek_per_m2', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author')),
            ],
            options={
                'db_table': 'constructions',
            },
        ),
        migrations.CreateModel(
            name='UnitDescription',
            fields=[
                ('field', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'unit_descriptions',
            },
        ),
        migrations.CreateModel(
            name='WindowGlazing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('optical_data_type', models.CharField(choices=[('SpectralAverage', 'Spectral Average'), ('Spectral', 'Spectral'), ('BSDF', 'BSDF'), ('SpectralAndAngle', 'Spectral and Angle')], max_length=20)),
                ('spectral_data_set', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness_m', models.FloatField()),
                ('conductivity_w_mk', models.FloatField(default=0.9)),
                ('solar_transmittance', models.FloatField(null=True)),
                ('front_solar_reflectance', models.FloatField(null=True)),
                ('back_solar_reflectance', models.FloatField(null=True)),
                ('visible_transmittance', models.FloatField(null=True)),
                ('front_visible_reflectance', models.FloatField(null=True)),
                ('back_visible_reflectance', models.FloatField(null=True)),
                ('infrared_transmittance', models.FloatField(default=0.0)),
                ('front_ir_emissivity', models.FloatField(default=0.84)),
                ('back_ir_emissivity', models.FloatField(default=0.84)),
                ('dirt_correction_factor', models.FloatField(default=1.0)),
                ('solar_diffusing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('youngs_modulus_pa', models.FloatField(default=72000000000.0)),
                ('poisson_ratio', models.FloatField(default=0.22)),
                ('angle_trans_table', models.TextField(blank=True, null=True)),
                ('angle_front_refl_table', models.TextField(blank=True, null=True)),
                ('angle_back_refl_table', models.TextField(blank=True, null=True)),
                ('gwp_kgco2e_per_m2', models.FloatField()),
                ('cost_sek_per_m2', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author')),
            ],
            options={
                'db_table': 'window_glazing',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('roughness', models.CharField(choices=[('VeryRough', 'Very Rough'), ('Rough', 'Rough'), ('MediumRough', 'Medium Rough'), ('MediumSmooth', 'Medium Smooth'), ('Smooth', 'Smooth'), ('VerySmooth', 'Very Smooth')], max_length=20)),
                ('thickness_m', models.FloatField()),
                ('conductivity_w_mk', models.FloatField()),
                ('density_kg_m3', models.FloatField()),
                ('specific_heat_j_kgk', models.FloatField()),
                ('thermal_absorptance', models.FloatField(default=0.9)),
                ('solar_absorptance', models.FloatField(default=0.7)),
                ('visible_absorptance', models.FloatField(default=0.7)),
                ('gwp_kgco2e_per_m2', models.FloatField()),
                ('cost_sek_per_m2', models.FloatField()),
                ('wall_allowed', models.BooleanField(default=False)),
                ('roof_allowed', models.BooleanField(default=False)),
                ('floor_allowed', models.BooleanField(default=False)),
                ('window_layer_allowed', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='ConstructionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author')),
                ('floor_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_sets', to='database.construction')),
                ('roof_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roof_sets', to='database.construction')),
                ('wall_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_sets', to='database.construction')),
                ('window_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_sets', to='database.construction')),
            ],
            options={
                'db_table': 'construction_sets',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_order', models.IntegerField()),
                ('is_glazing_layer', models.BooleanField(default=False)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='database.construction')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.material')),
                ('window', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.windowglazing')),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['layer_order'],
                'unique_together': {('construction', 'layer_order')},
            },
        ),
    ]
