# Generated by Django 3.2.25 on 2025-09-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='construction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='constructionset',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False},
        ),
    ]
