# Generated by Django 3.2.25 on 2025-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_create_material_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='roughness',
            field=models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('MediumSmooth', 'MediumSmooth'), ('MediumRough', 'MediumRough'), ('Rough', 'Rough'), ('VeryRough', 'VeryRough')], max_length=20, null=True),
        ),
    ]
