# Generated by Django 3.2.25 on 2025-09-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_add_material_roughness_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author'),
        ),
        migrations.AddField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='density_kg_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='floor_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='roof_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='solar_absorptance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='specific_heat_j_kgk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='thermal_absorptance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='visible_absorptance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='wall_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='window_layer_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
