from django.db import migrations
import uuid

def load_materials(apps, schema_editor):
    Material = apps.get_model('database', 'Material')
    materials = [
        {
            'id': uuid.UUID('c4cc73d9-ff3e-4ef4-b5b5-cf4eb517c1ab'),
            'name': 'Brick',
            'roughness': 'MediumRough',
            'thickness_m': 0.1016,
            'conductivity_w_mk': 0.89,
            'density_kg_m3': 1920,
            'specific_heat_j_kgk': 790,
            'thermal_absorptance': 0.9,
            'solar_absorptance': 0.7,
            'visible_absorptance': 0.7,
            'gwp_kgco2e_per_m2': 85.2,
            'cost_sek_per_m2': 450,
            'wall_allowed': True,
            'roof_allowed': False,
            'floor_allowed': False,
            'window_layer_allowed': False,
            'created_at': '2025-05-25T12:40:12.901990+02:00',
        },
        {
            'id': uuid.UUID('482ea462-0e92-4a97-aad4-a4af99dfc9df'),
            'name': 'Insulation Fiberglass',
            'roughness': 'MediumRough',
            'thickness_m': 0.0889,
            'conductivity_w_mk': 0.043,
            'density_kg_m3': 12,
            'specific_heat_j_kgk': 840,
            'thermal_absorptance': 0.9,
            'solar_absorptance': 0.7,
            'visible_absorptance': 0.7,
            'gwp_kgco2e_per_m2': 12.5,
            'cost_sek_per_m2': 120,
            'wall_allowed': True,
            'roof_allowed': True,
            'floor_allowed': True,
            'window_layer_allowed': False,
            'created_at': '2025-05-25T12:40:12.901990+02:00',
        },
        {
            'id': uuid.UUID('647d1be6-7899-4ac5-8b4c-05551db16b6d'),
            'name': 'Concrete Block',
            'roughness': 'MediumRough',
            'thickness_m': 0.2032,
            'conductivity_w_mk': 0.51,
            'density_kg_m3': 1400,
            'specific_heat_j_kgk': 1000,
            'thermal_absorptance': 0.9,
            'solar_absorptance': 0.7,
            'visible_absorptance': 0.7,
            'gwp_kgco2e_per_m2': 120.4,
            'cost_sek_per_m2': 380,
            'wall_allowed': True,
            'roof_allowed': False,
            'floor_allowed': True,
            'window_layer_allowed': False,
            'created_at': '2025-05-25T12:40:12.901990+02:00',
        },
        {
            'id': uuid.UUID('c16e762e-08b4-4221-84d8-5def42b6e2c7'),
            'name': 'Gypsum Board',
            'roughness': 'Smooth',
            'thickness_m': 0.0127,
            'conductivity_w_mk': 0.16,
            'density_kg_m3': 800,
            'specific_heat_j_kgk': 1090,
            'thermal_absorptance': 0.9,
            'solar_absorptance': 0.7,
            'visible_absorptance': 0.7,
            'gwp_kgco2e_per_m2': 7.2,
            'cost_sek_per_m2': 85,
            'wall_allowed': True,
            'roof_allowed': True,
            'floor_allowed': False,
            'window_layer_allowed': False,
            'created_at': '2025-05-25T14:56:06.655458+02:00',
        },
        {
            'id': uuid.UUID('9a29b2a4-8eba-4c86-9dbd-829014c09765'),
            'name': 'Wood Siding',
            'roughness': 'MediumSmooth',
            'thickness_m': 0.0191,
            'conductivity_w_mk': 0.14,
            'density_kg_m3': 530,
            'specific_heat_j_kgk': 900,
            'thermal_absorptance': 0.9,
            'solar_absorptance': 0.7,
            'visible_absorptance': 0.7,
            'gwp_kgco2e_per_m2': 8.3,
            'cost_sek_per_m2': 175,
            'wall_allowed': True,
            'roof_allowed': False,
            'floor_allowed': False,
            'window_layer_allowed': False,
            'created_at': '2025-05-25T14:56:06.655458+02:00',
        },
    ]
    for mat in materials:
        Material.objects.update_or_create(id=mat['id'], defaults=mat)

class Migration(migrations.Migration):
    dependencies = [
        ('database', '0003_update_material_schema'),
    ]
    operations = [
        migrations.RunPython(load_materials),
    ]
