# Generated by Django 3.2.25 on 2025-09-22 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_load_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_simulations', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.author')),
            ],
            options={
                'db_table': 'scenarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScenarioConstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('wall', 'Wall'), ('roof', 'Roof'), ('floor', 'Floor'), ('ceiling', 'Ceiling'), ('window', 'Window')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.construction')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_constructions', to='database.scenario')),
            ],
            options={
                'db_table': 'scenario_constructions',
                'managed': True,
            },
        ),
    ]
