title: EPSM Documentation
description: Docs for the Energy Performance Simulation Manager
theme: minima
# For GitHub project pages (https://<user>.github.io/epsm) set the baseurl to the repo name.
baseurl: "/epsm"
defaults:
  - scope:
      path: "" # all files
      type: "pages"
    values:
      layout: default
exclude:
  - node_modules
  - .github
