# Generated by Django 3.2.25 on 2025-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
