# Generated by Django 3.2.25 on 2025-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_simulation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='file_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulationfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
