# Generated by Django 5.2.6 on 2025-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulation_progress'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simulationresult',
            name='simulation__simulat_55e4dc_idx',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='simulation',
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='simulation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['simulation_id', 'run_id'], name='simulation__simulat_55e4dc_idx'),
        ),
    ]
