# Generated by Django 5.2.6 on 2025-09-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20250529_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('total_energy_use', models.FloatField(blank=True, null=True)),
                ('heating_demand', models.FloatField(blank=True, null=True)),
                ('cooling_demand', models.FloatField(blank=True, null=True)),
                ('lighting_demand', models.FloatField(blank=True, null=True)),
                ('equipment_demand', models.FloatField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('variant_idx', models.IntegerField(blank=True, null=True)),
                ('idf_idx', models.IntegerField(blank=True, null=True)),
                ('construction_set_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.simulation')),
            ],
            options={
                'db_table': 'simulation_results',
            },
        ),
        migrations.CreateModel(
            name='SimulationEnergyUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_use', models.CharField(max_length=100)),
                ('electricity', models.FloatField(default=0.0)),
                ('district_heating', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_uses', to='simulation.simulationresult')),
            ],
            options={
                'db_table': 'simulation_energy_uses',
            },
        ),
        migrations.CreateModel(
            name='SimulationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
                ('area', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('simulation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='simulation.simulationresult')),
            ],
            options={
                'db_table': 'simulation_zones',
            },
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['simulation', 'run_id'], name='simulation__simulat_55e4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['variant_idx', 'idf_idx'], name='simulation__variant_707f67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationenergyuse',
            unique_together={('simulation_result', 'end_use')},
        ),
    ]
