# Generated by Django 3.2.25 on 2025-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_add_user_and_hourly_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['user_id'], name='simulation__user_id_e5a3e9_idx'),
        ),
    ]
