name: Jekyll Build Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: |
          gem install bundler
          bundle install
        working-directory: docs

      - name: Build site
        run: bundle exec jekyll build --source . --destination _site
        working-directory: docs

      - name: List built files
        run: ls -la _site | head -n 50
        working-directory: docs
