name: Publish Docs

on:
  push:
    branches: [ main ]

# Request explicit permissions so the GITHUB_TOKEN can push the built site.
# If your organization restricts GITHUB_TOKEN write permissions, create a
# personal access token (repo scope) and store it as the secret GH_PAGES_PAT
# then uncomment the `personal_token` input below and add the secret.
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --site-dir site

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site

      - name: Deploy to GitHub Pages (actions/deploy-pages)
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        # The action will use the provided GITHUB_TOKEN; ensure the workflow
        # permissions include 'pages: write' (already declared above).
